### ISSUE TITLE
"No documentation found" page leaves artifacts from previously viewed element

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/iron-component-page#27]
Example from paper-styles

![Example of Problem](https://cloud.githubusercontent.com/assets/522948/7821106/613c9c3a-03a1-11e5-8434-1a1bf85c7900.png)

/cc @justinfagnani 

Moved from Polymer/polymer-element-catalog#57

**Comment by notwaldorf** [comment]
Is this still happening? I cant repro it anymore, but please re-open this if it's still happening

**Comment by tobyroworth** [comment]
Sorry to comment on an old bug, but this seems to still be an issue for me. I think I've found the problem/a solution though.

`#nodocs`, the bit that says "No documentation found" is
```
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
```
 (comes from `--layout-fit`) so gets sized to it's first positioned parent (or similar).

This means that `#nodocs` can end up getting sized based on `#mainContainer`, which can end up smaller than its children, so `#nodocs` doesn't necessarily cover all of `iron-doc-viewer` which is where these artifacts come from.

To me, the easiest way to fix this is to make `#docs`, which is `#nodocs` and `iron-docs-viewer` immediate parent, `position: relative;` so that `#nodocs` will fill _it_, hence covering `iron-doc-viewer`.

As a workaround, the `--iron-component-page-container` can be used to make `#docs` relative
```
	iron-component-page {
		--iron-component-page-container: {
			position: relative;
		}
	}
```

Is it worth putting a PR in for something this trivial?

**Comment by tobyroworth** [comment]
Thinking about it, this does mean that the "No document found" might not be seen, so a more involved solution could be worthwhile. Setting the `hidden` attribute on `iron-doc-viewer` might be better that positioning `#docs`?

To quickly reproduce the problem, head to https://elements.polymer-project.org/elements/paper-button and set a height (0 will work) on `#mainContainer` in `iron-component-page` and remove the `hidden` attribute on the `#nodocs` div.
